
project_id = "dqkrmewgeeuxhbxrwpjp"

[functions.translate]
verify_jwt = true

[functions.translate-deepl]
verify_jwt = true

[functions.translate-openai]
verify_jwt = true

[functions.public_menu_bundle]
verify_jwt = false

[functions.get_paypal_client_id]
verify_jwt = true
