export const LAYOUTS_STORAGE_KEY = "menu_print_layouts";

export const PRINT_CONSTANTS = {
  MM_TO_PX: 3.78,
  A4_WIDTH_MM: 210,
  A4_HEIGHT_MM: 297,
  DEFAULT_MARGINS: {
    TOP: 20,
    RIGHT: 15,
    BOTTOM: 20,
    LEFT: 15
  },
  ESTIMATED_HEIGHTS: {
    CATEGORY_TITLE: 60,
    PRODUCT_BASE: 35,
    PRODUCT_DESCRIPTION_SHORT: 25,
    PRODUCT_DESCRIPTION_MEDIUM: 35,
    PRODUCT_DESCRIPTION_LONG: 50,
    PRODUCT_ALLERGENS: 15,
    PRODUCT_PRICE_VARIANTS: 25
  },
  SPACING: {
    BETWEEN_CATEGORIES: 18,
    BETWEEN_PRODUCTS: 6
  }
};
