
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqkrmewgeeuxhbxrwpjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxa3JtZXdnZWV1eGhieHJ3cGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDg3MDksImV4cCI6MjA2MjE4NDcwOX0.Crs-I0mmm8vEQh8eUQPjWShRl6eTaOFGdwaZKWFG7t0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
